# Generated by Django 5.1.2 on 2024-10-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fase_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('progreso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.TextField()),
                ('compost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.compost')),
            ],
        ),
    ]
